name: flutter_opengl_example
description: Demonstrates how to use the flutter_opengl plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_opengl:
    path: ../

  cupertino_icons: ^1.0.2

  #https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.1.3

  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.7

  #https://pub.dev/packages/star_menu
  star_menu: ^3.1.3

  #https://pub.dev/packages/file_picker
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
   - family: JetBrains
     fonts:
       - asset: assets/JetBrainsMono-Regular.ttf
