name: flutter_opengl
description: Flutter OpenGL plugin
version: 0.0.3
author: Marco Bavagnoli <marcobavagnolidev@gmail.com>
homepage: https://github.com/alnitak/flutter_opengl

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bavagnoli.opengl
    pluginClass: OpenglPlugin

