name: flutter_opengl
description: Flutter plugin to bind a Texture widget to an OpenGL ES context. Many ShaderToy shaders can be used
version: 0.9.0
homepage: https://github.com/alnitak/flutter_opengl

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

  #https://pub.dev/packages/ffi
  ffi: 2.0.1

  #https://pub.dev/packages/image
  image: ^4.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  #https://pub.dev/packages/ffigen
  ffigen: ^7.2.4

ffigen:
  output: './lib/flutter_opengl_ffi_TMP.dart'
  name: 'FlutterOpenGLFfi'
  description: 'Bindings to Flutter_OpenGL'
  functions:
    exclude:
      - 'getVisualizer'
  headers:
    entry-points:
      - 'ppp.h'
    include-directives:
      - '**ppp.h'
  unnamed-enums:
    include:
      - 'CX_.*'
    exclude:
      - '.*Flag'
    rename:
      'CXType_(.*)': '$1'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.flutter_opengl
        pluginClass: FlutterOpenglPlugin
      ios:
        pluginClass: FlutterOpenglPlugin
      linux:
        pluginClass: FlutterOpenglPlugin
      macos:
        pluginClass: FlutterOpenglPlugin
      windows:
        pluginClass: FlutterOpenglPluginCApi

